name: Build, Test and Push Docker Image

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Pega o código do repositório
      - name: Checkout do código
        uses: actions/checkout@v3
        
      # 2. Login no Docker Hub
      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Garante que o JDK 21 seja instalado
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'     
          distribution: 'temurin'
          cache: maven

      # 4. Buil do Java 
      - name: Build com Maven
        run: mvn clean package -DskipTests

      # 5. Criar rede 
      - name: Criar rede docker 
        run: docker network create movieflix-net
      
      # 6. Subir Postgres 
      - name: Rodar Postgres 
        run: | 
          docker run -d --name postgres-dados --network movieflix-net -e POSTGRES_USER=user -e POSTGRES_PASSWORD=secret -e POSTGRES_DB=movieflix-db -p 5432:5432 postgres:15 
          sleep 15
     
      # 7. Ler arquivos .csv e incluir dados no banco
      - name: Build e Run ETL
        run: |
          docker build -t etl-postgres ./Postgres
          docker run --rm --name etl-run --network movieflix-net -v ${{ github.workspace }}/Postgres/data:/app/data -e PG_USER=user -e PG_PASS=secret -e PG_DB=movieflix-db -e PG_HOST=postgres-dados etl-postgres
          sleep 10
          
      # 8. Rodar aplicação 
      - name: Build e run da aplicação 
        run: | 
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/movieflix-app:latest .
          docker run -d --name movieflix --network movieflix-net -e DB_HOST=postgres-dados -e DB_USER=user -e DB_PASSWORD=secret -e DB_NAME=movieflix-db ${{ secrets.DOCKERHUB_USERNAME }}/movieflix-app:latest
          sleep 20
        
      # 9. Build e rodar Nginx 
      - name: Build e run Nginx proxy 
        run: | 
          docker build -t movieflix-nginx ./Proxy-reverso 
          docker run -d --name proxy --network movieflix-net -p 80:80 movieflix-nginx 
          sleep 10  
      
      # 10. Teste via proxy reverso 
      - name: Testar aplicação via Nginx 
        run: | 
          curl -f http://localhost:80/ || (echo "Teste falhou" && exit 1)

      # 11. Push da imagem para o Docker Hub 
      - name: Push da imagem 
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/movieflix-app:latest  

      # 12. Limpeza
      - name: Limpar containers e rede
        if: always()
        run: |
          echo "Parando e removendo containers e rede temporários..."
          docker stop postgres-dados movieflix proxy etl-run || true
          docker rm postgres-dados movieflix proxy etl-run|| true
          docker network rm movieflix-net || true
